m1=int (input("Enter Enter student number m1:  "))
m2=int (input("Enter Enter student number m2:  "))
m3=int (input("Enter Enter student number m3:  "))
m4=int (input("Enter Enter student number m4:  "))
m5=int (input("Enter Enter student number m5:  "))
m6=int (input("Enter Enter student number m6:  "))
m7=int (input("Enter Enter student number m7:  "))
studentn_nubmer=[m1,m2,m3,m4,m5,m6,m7]
studentn_nubmer.sort()
print(studentn_nubmer)